### ISSUE TITLE
Cant add class to list, listDropdown

### ISSUE THREAD

**Issue by rkorupaev** [Choices-js/Choices#966] opened 2021-08-18 09:29 UTC
**Describe the bug**
Good day. While using classNames field, cant add class to list or listDropdown (mb more, didnt check all). First two lines is good, tried with Item, works ok. 

**To Reproduce**
Think it is easy to reproduce, just see the screenshots.

**Expected behavior**
Expecting to add my class to an element.

**Screenshots**
![изображение_2021-08-18_122658](https://user-images.githubusercontent.com/23292575/129873895-97357661-7636-4b92-9bc8-f8fd7df0f6dd.png)

![image](https://user-images.githubusercontent.com/23292575/129874193-e6403374-3cb8-4260-a1f0-b7b48eeaac48.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera
 - Version: 78.0.4093.147

**Comment by mtriff** [comment] 2021-12-23 03:57
Duplicate of #832, PR is pending at #889.

**Closed by mtriff** 2021-12-23 03:57 UTC
Labels: bug
