### ISSUE TITLE
Menu not closing in item click or click outside --- only in Safari

### ISSUE THREAD

**Issue by atstockland** [Choices-js/Choices#1100] opened 2023-01-29 20:21 UTC
**Describe the bug**
Menu exposes when clicked on, as expected, however does not close after clicking an item or clicking outside the menu.  Even the DEMO page suffers from this.  I have confirmed this issue does not exist in Chrome or FireFox.  It seems to only exist in Safari.

**To Reproduce**
1. Go to the choices.js DEMO page on Safari, expose the "Multiple select input" or any select menu that exposes a dropdown (like Option groups).
2.  Notice the menu area will not close after selecting an item or clicking outside of the menu

**Expected behavior**
Safari should act the same as the other browsers

**Desktop (please complete the following information):**
 - OS: MacOS
 - iOS: this also occurs 16.1.1
 - Safari 16.1

**Comment by belabedmedoussama** [comment] 2023-02-01 00:37
you should add this to your css code 
```
.choices__list--dropdown{
.....
....
transform: translate3d(0, 0, 200px);
}
```

**Comment by atstockland** [comment] 2023-02-01 03:26
Thanks @belabedmedoussama.  That solution does work to fix the issue.  It seems like a bug in the library though, that shouldn't require any css tweaks.  My app is working better thanks to you suggestion.

**Comment by ezitisitis** [comment] 2023-02-24 21:35
Looks like a duplicate of: https://github.com/Choices-js/Choices/issues/1056

**Closed** 2024-08-27 23:25 UTC
Labels: bug
