### ISSUE TITLE
Search input can't be selected when accessed with navigation arrows.

### ISSUE THREAD

**Issue by ruipmendes** [Choices-js/Choices#935] opened 2021-03-12 17:27 UTC
When navigating the screen using tab and other keyboard shortcuts, the search becomes unavailable to focus if the dropdown is open using the directional keys (arrows).

**To Reproduce**
1. Go to the sample page.
2. Use tab until you have the «Single select input» «Default» dropdown selected.
3.1 Use 'enter' or 'space' to open: the search input is focused.
3.2 Use the 'arrow-down' to open: the search input is not focused and can't be focused by clicking.

**Expected behavior**
The search input should open focused.  Alternatively, the dropdown opens with the first option highlighted.
The search input Must be focuseable.

**Screenshots**
![input focus](https://user-images.githubusercontent.com/45291168/110975731-0473f100-8358-11eb-9c2b-d2fdbd53043b.gif)

**Desktop:**
 - OS: Windows10
 - Browser chrome

**Comment by bmarcelino-fe** [comment] 2021-05-14 10:37
@ruipmendes I found the same problem and to fix this I made this change:
I changed the validation on this js snippet from this `this.showDropdown(),this._canSearch=!1` to this `this.showDropdown(),this._canSearch=!0`.

I'm not sure if this is the best solution because we are changing the default behavior of Choices but I can't found any other solution.

@Spone @Moeriki @rstacruz @travist I don't know if You can help us but they are the only that can appear on this track to identify:

- Could you help us with this issue?
- My solution is the right one?
- With this fix, what can be affected? any breaking changes on Choices behavior?

Thanks
Bruno Marcelino

**Comment by iAmKevinMcKee** [comment] 2023-07-26 17:08
First, thanks for providing a great package!

This bug is still hanging around. Just curious if there are any plans to fix it? Thank you!

**Comment by kg-currenxie** [comment] 2024-03-26 03:23
This is still an issue..

**Comment by kg-currenxie** [comment] 2024-06-13 04:51
@iAmKevinMcKee that commit did not work for me, still see "arrowdown" in the input. Commit applied with `patch-package`

**Comment by KaueGSouzaDevs** [comment] 2024-10-28 16:06
Any news about this issue?

**Comment by zoglo** [comment] 2024-12-23 11:37
See #1230 (the duplicate of this issue)

**Comment by Xon** [comment] 2024-12-24 14:19
This is fixed for v11.0.3, which I'll do a release for on the 26th

**Closed by Xon** 2024-12-24 14:19 UTC
Labels: bug
