### ISSUE TITLE
[v11] possible regression: "noChoicesText" not appearing

### ISSUE THREAD

**Issue by tagliala** [Choices-js/Choices#1185] opened 2024-08-30 17:15 UTC
**Describe the bug**
Hello, I've tried to figure out if there was a breaking change but I couldn't find it

**To Reproduce**
1. Go to https://jsfiddle.net/tagliala/rx8mtbz6/6 Based on Choices 10
2. Click on the input field
3. `noChoicesText` does not Appear
  
On v10.2, the field appears: https://jsfiddle.net/tagliala/rx8mtbz6/9

NOTE: Even if in the readme states that this feature is only available with `select-multiple`, I think it is a problem in the documentation, because it worked also on `select-one`. Also, on v11 does not work on both select-single and select-multiple

Ref: https://github.com/Choices-js/Choices/tree/v10.2.0?tab=readme-ov-file#nochoicestext

**Expected behavior**
See "Hello World"

**Screenshots**

### v10
<img width="519" alt="image" src="https://github.com/user-attachments/assets/2d2721eb-7b5d-4a3b-a967-589736577849">

### v11
<img width="517" alt="image" src="https://github.com/user-attachments/assets/048bafe8-8335-4f9e-bd53-aa47517fe0e0">

**Choices version and bundle**
- Version: 11.0.1

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome / Firefox
 - Version 128.0.6613.114 / 129.0.2 (64 bit)

**Comment by Xon** [comment] 2024-08-30 22:09
How "no choices" (and other notices) where displayed where overhauled, and it looks like this case was missed.

The e2e test suit only tested this with `select-multiple`, so it is likely it was missed for `select-single`.

**Comment by Xon** [comment] 2024-08-30 23:06
I've added some more end-to-end tests to cover this, and adjusted how the `noChoicesText` option is used.

There was another regression in that disabled choices where considered selectable for this option. This does mean if all the choices are disabled it'll show the `noChoicesText` option but I think that is acceptable.

**Comment by Xon** [comment] 2024-08-30 23:26
I've merged in #1187 which fixes this. This will likely be released towards the end of next week

**Closed by Xon** 2024-08-30 23:26 UTC
Labels: bug

**Comment by tagliala** [comment] 2024-08-31 06:58
Thanks, this new release fixed a lot of issues we were having and we could remove a lot of workarounds
