### ISSUE TITLE
"No choices to choose from" message doesn't get removed

### ISSUE THREAD

**Issue by ultish** [Choices-js/Choices#1247] opened 2024-12-27 03:34 UTC
**Describe the bug**
In a multiple select input after you have selected all the available choices, the message "No choices to choose from" will appear. However, if you remove one of your items and open the dropdown menu again, that same "No choices to choose from" is still there even though 1 choice is available now.

**To Reproduce**
1. In the demo website https://choices-js.github.io/Choices/ on the Multiple select input with remove button, select all 4 choices
2. "No choices to choose from" should now appear
3. Delete one of the selected items and open the drop down again
4. You'll now see a single choice and the "No choices to choose from"

**Expected behavior**
The "No choices to choose from" should disappear once a choice is available again

**Screenshots**
<img width="513" alt="image" src="https://github.com/user-attachments/assets/37fb89c1-123e-416a-8e01-6d34fdbc088f" />

**Choices version and bundle**
- Version: v11.0.2

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome
 - Version 131

**Comment by Xon** [comment] 2024-12-27 18:42
Duplicate of #1212 
A fixed release (v11.0.3) will be prepared in the next day or so

**Closed by Xon** 2024-12-27 18:42 UTC
Labels: bug
