### ISSUE TITLE
Dropdown doesn't close after selection or not closing properly in Safari

### ISSUE THREAD

**Issue by hosaruzu** [Choices-js/Choices#1056] opened 2022-09-14 14:46 UTC
**Describe the bug**
In Safari dropdown doesn't close after selection, or it leaves behind an empty space the size of a dropdown.

**To Reproduce**
1. Go to 'https://choices-js.github.io/Choices/'
2. Click on 'Single select input -> Default'
3. Select value / or change focus / or click on page for closing 

**Screenshots**
<img width="519" alt="Screenshot 2022-09-14 at 18 44 32" src="https://user-images.githubusercontent.com/25340589/190186955-545041e6-87e0-4201-adad-03bf454a94b2.png">
<img width="509" alt="Screenshot 2022-09-14 at 18 44 43" src="https://user-images.githubusercontent.com/25340589/190186992-a89fb5dd-83db-44f5-a649-82b5f7879067.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6 21G115
 - Browser: Safari 
 - Version 16.0 (17614.1.25.9.10, 17614)

**Comment by teknetia** [comment] 2022-09-19 00:30
I'm also seeing this, as are a bunch of folks I got to test it to make sure it wasn't caused by content or ad blockers. I also note the following behaviour based on my testing:

1. Go to 'https://choices-js.github.io/Choices/'
2. Click on 'Single select input -> Default'
3. Select value / or change focus / or click on page for closing
4. See error
5. Focus on another window (another Safari window, the desktop, anything at all)
6. Within a few moment (or on return to the Safari window with the page in it) the leftover element will disappear.

I've noticed on a page where I have some text appear based on the selected item the empty box appears too, but it is behind everything else rather than on top of it so just looks like a real odd visual artefact.

**Comment by MrMooky** [comment] 2022-09-20 18:47
Started happening with the latest Safari update.

**Comment by karlcow** [comment] 2022-09-30 04:35
Tracked at rdar://100048880 in Apple.

**Comment by samlanson** [comment] 2022-10-03 11:52
As a temporary workaround, I applied the below CSS and it works for me. 

```
.choices .choices__list.choices__list--dropdown { 
  visibility: visible !important;
}
.choices .choices__list--dropdown,
.choices .choices__list[aria-expanded]{
  margin-top: 0px;
}
.choices.is-open .choices__list--dropdown, 
.choices.is-open .choices__list[aria-expanded]{
  margin-top: -1px;
}
```

**Comment by karlcow** [comment] 2022-11-01 03:20
This might be because of https://bugs.webkit.org/show_bug.cgi?id=240728
(still investigating)

**Comment by zacol** [comment] 2022-12-03 22:12
The same error occurs on Safari on iOS.

**Comment by karlcow** [comment] 2022-12-06 06:04
https://bugs.webkit.org/show_bug.cgi?id=240728 has been fixed.
It will be available probably in a future release of Safari.

**Comment by justdesigned** [comment] 2023-01-24 10:46
It may be useful to someone - I`ve added "transform: translate3d(0,0,0)" to the dropdown open class and it works

**Comment by karlcow** [comment] 2023-02-13 04:54
@AshwinNS the best way to test is STP 163 at the moment. 
But yes this is fixed in STP 163.

**Closed** 2024-08-27 23:25 UTC
Labels: bug
