### ISSUE TITLE
[v11] `main` branch: Regression in "no choices text" when clearing search field

### ISSUE THREAD

**Issue by tagliala** [Choices-js/Choices#1191] opened 2024-08-31 10:41 UTC
**Describe the bug**
Hello, this is a follow up of #1185

**To Reproduce**
1. Go to https://jsfiddle.net/tagliala/rx8mtbz6/13 Based on Choices 11 (main)
2. Click on the input field
3. Insert a letter
4. Delete the letter
5. `noChoicesText` does not Appear
  
On v10.2, the text appears: https://jsfiddle.net/tagliala/rx8mtbz6/9

**Expected behavior**
See "Hello World"

**Screenshots**

### v10

<img width="517" alt="image" src="https://github.com/user-attachments/assets/68631229-876f-4abd-b1e0-9d1089aab2d7">

### v11

<img width="521" alt="image" src="https://github.com/user-attachments/assets/e5c762c2-f473-40bc-af1d-8930dfd0da37">

**Choices version and bundle**
- Version: main

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome / Firefox
 - Version 128.0.6613.114 / 129.0.2 (64 bit)

**Comment by tagliala** [comment] 2024-08-31 10:45
I think that there are other regression with the search functionality, related to how `noChoicesText` and `noResultsText` are being used, but I'm not confident to share the results at the moment, I prefer to provide reproducible test cases (and maybe the issues are related)

**Comment by Xon** [comment] 2024-08-31 11:50
Thanks for identifying this, it looks like this is going to need more work on when `noChoicesText` or `noResultsText` is displayed

**Comment by Xon** [comment] 2024-08-31 11:57
I've added an e2e test which reproduces the issue, but it will be in a day or so before I can dig into the notice display logic for this

**Comment by tagliala** [comment] 2024-08-31 12:00
No problems, thanks for your support

**Comment by Xon** [comment] 2024-08-31 12:14
PR #1192 *should* work better, it cleaned up some possible issues with no results vs no choices. I haven't had time to fully test it and see if any of the other end-to-end tests need updating to verify the behavior is working properly.

**Comment by Xon** [comment] 2024-09-04 11:38
@tagliala `main` should have the most recent rounds of fixes. If nothing else is reported I plan to release v11.0.2 at the end of the week

**Comment by Xon** [comment] 2024-09-04 17:52
This is encountering a few issues:
- `'search'` event is getting an empty query string to signal the search has stopped. Which happens on `setChoices` with replace is being called.
- `clearChoices()` is removing items. 
   Items/choices as separate objects caused a lot of internal complexity, and it was documented in v11.0.0 around this design change. This sadly doesn't work well with using choices as autocomplete. 

   I think a better public API may be the solution.
- `clearChoices()` is removing the "is searching flag", this is bug. But it was masking an issue inside `setChoices()`
- `setChoices()` isn't setting the "rank" value on the Choice internally which results in the values being filtered out when in "search" mode. It previously sorted on non-unique score, but this could result in an unstable sort.

**Comment by Xon** [comment] 2024-09-04 19:33
I've adjusted `setChoices`/`clearChoices` to hopefully be less surprising, which should work better.

There are still some minor behavior differences (how selected items/choices show up), but I think it is acceptable without major changes.

**Comment by Xon** [comment] 2024-09-07 01:17
`v11.0.2` has a few more bugfixes, and should be in a much better state. There is now an autocomplete e2e test based on your snippet should should catch regressions

**Closed by Xon** 2024-09-07 01:17 UTC
Labels: bug

**Comment by tagliala** [comment] 2024-09-07 07:26
Thanks, I've tested the main branch and it now works better

I've switched to `searchFloor` instead of early returning from `search` when there are less than two chars, it is not exactly the same behavior as before but works better overall
